"""Run the built-in sample assessment (348 cameras, 1,000 employees, mixed/
unknown camera specs, existing NVR, unknown GPU; restricted-zone, occupancy
and PPE) through the Solution Designer and print the key outcomes.

    python scripts/sample_assessment.py            # print summary
    python scripts/sample_assessment.py --html out.html   # also write the report
    python scripts/sample_assessment.py --json out.json   # also dump the full result
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.solution_designer.engine import run_assessment  # noqa: E402
from backend.solution_designer.narrative import _fmt_inr  # noqa: E402
from backend.solution_designer.report import render_html  # noqa: E402
from backend.solution_designer.sample import sample_request  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", help="write the print-ready HTML report here")
    ap.add_argument("--json", help="write the full assessment JSON here")
    args = ap.parse_args()

    req = sample_request()
    a = run_assessment(req)
    s = a["suitability_summary"]

    print("SOUVENO VISION SOLUTION DESIGNER — SAMPLE ASSESSMENT")
    print(f"Client: {req.client.company_name} · Site: {req.site.name} · Employees: {req.site.employees} · Cameras: {s['total_cameras']}")
    print(f"Use cases: {', '.join(req.requirements.use_cases)}")
    print()
    print("Camera suitability")
    for r in a["suitability"]:
        flag = " [BLOCKED: " + r["hard_blockers"][0] + "]" if r["hard_blockers"] else (" [site validation required]" if r["validation_items"] else "")
        print(f"  {r['classification']} {r['score']:>3}/100  {r['count']:>3}×  {r['label']}{flag}")
    print(f"  → candidate AI cameras (A+B): {s['candidate_ai_cameras']} · unsuitable (D): {s['by_class']['D']['cameras']} · need validation: {s['validation_required_cameras']}")
    print()
    print("Deterministic calculations")
    for c in a["calculations"].values():
        val = "unknown" if c["value"] is None else f"{c['value']} {c['unit']}"
        print(f"  {c['name']}: {val}    [{c['formula']}]")
    print()
    print("Compute")
    print(f"  GPU status: {a['compute']['gpu_status']}")
    for w in a["compute"]["warnings"]:
        print(f"  ! {w}")
    print(f"  {a['compute']['capacity_statement']}")
    print()
    p = a["pilot"]
    print(f"Pilot: {p['duration_days']} days · {p['camera_count']} cameras · areas {p['areas']} · use cases {[u['id'] for u in p['use_cases']]}")
    print()
    est = a["commercial"]
    print(f"Commercial ({est['status'].split(' — ')[0]}) for {est['active_ai_cameras']} candidate cameras")
    print(f"  Monthly licence: {_fmt_inr(est['monthly_licence']['ex_gst'])} + GST {_fmt_inr(est['monthly_licence']['gst'])}")
    print(f"  One-time (pilot + implementation): {_fmt_inr(est['one_time_total']['ex_gst'])} + GST")
    print(f"  First-year total: {_fmt_inr(est['first_year_total']['ex_gst'])} + GST {_fmt_inr(est['first_year_total']['gst'])}")
    print(f"  Hardware: {est['hardware']}")
    print()
    print(f"DECISION: {a['decision']['recommendation']} — final hardware recommended: {a['decision']['final_hardware_recommended']}")
    print(f"  {a['decision']['reason']}")
    print(f"Narrative generated by: {a['narrative_generated_by']}")

    if args.html:
        Path(args.html).write_text(render_html(a), encoding="utf-8")
        print(f"\nReport written to {args.html}")
    if args.json:
        Path(args.json).write_text(json.dumps(a, indent=2, default=str), encoding="utf-8")
        print(f"Full result written to {args.json}")


if __name__ == "__main__":
    main()
